name: Deploy RDS with Terraform

on:
  push:
    branches:
      - main

env:
  REGION_DEFAULT: "us-east-1"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: aws-lab-fiap

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: ${{env.REGION_DEFAULT}}

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform with Secrets
        run: terraform apply -auto-approve
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_name: ${{ secrets.DB_NAME }}
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}